icu/apps/lending/urls.py
from django.conf.urls import patterns, url
from icu.apps.lending.views import ItemList, calendar, calendar_lendings, borrow


urlpatterns = patterns('',
    url(r'^$', ItemList.as_view(), {}, "item_list"),
    url(r'^calendar/$', calendar, {}, "calendar"),
    url(r'^calendar/lendings/$', calendar_lendings, {}, "calendar_lendings"),
    url(r'^borrow/$', borrow, {}, "borrow"),
)

icu/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',TemplateView.as_view(template_name="documentation.html")),
    url(r'^lending/', include('icu.apps.lending.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',  #
            {'document_root': settings.STATIC_ROOT}),               # Remove these two urls
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',   # in production
            {'document_root': settings.MEDIA_ROOT}),                #
)

icu/apps/lending/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='item_images', blank=True, default="item_images/no_image.png")
    lending_duration = models.IntegerField(blank=True, null=True)
    locked = models.BooleanField(default=False, blank=True)

    def __unicode__(self):
        return self.name


class Lending(models.Model):
    user = models.ForeignKey(User)
    item = models.ForeignKey(Item)
    start_date = models.DateField()
    end_date = models.DateField()
    comment = models.TextField(blank=True)

    def __unicode__(self):
        return self.item.name

icu/apps/lending/forms.py
# -*- coding: utf-8 -*-
from datetime import date, timedelta
from django import forms
from django.db.models import Q
from icu.apps.lending.models import Lending, Item


class LendingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(LendingForm, self).__init__(*args, **kwargs)
        self.fields['item'].queryset = Item.objects.exclude(locked=True)

    def clean(self):
        cleaned_data = super(LendingForm, self).clean()
        start_date = cleaned_data.get('start_date', None)
        end_date = cleaned_data.get('end_date', None)
        item = cleaned_data.get('item', None)
        if not (start_date and end_date and item):
            return cleaned_data
        if start_date < date.today():
            raise forms.ValidationError("The start date entered is less than today's date.")
        if end_date < start_date:
            raise forms.ValidationError("The end date entered is less than the start date.")
        if item:
            if item.lending_duration and end_date - start_date > timedelta(days=item.lending_duration):
                raise forms.ValidationError("The duration entered is greater than the maximun duration allowed for this item.")
            lendings = Lending.objects.filter(Q(item=item),
                                              Q(start_date__lte=start_date, end_date__gte=end_date) |
                                              Q(start_date__range=(start_date, end_date)) |
                                              Q(end_date__range=(start_date, end_date))
                                              ).distinct()
            if len(lendings) > 0:
                raise forms.ValidationError("Item not available at the dates you entered.")
        return cleaned_data

    class Meta:
        model = Lending
        exclude = ('user', )
        widgets = {
            "item": forms.Select(attrs={"class": "form-control", "onchange": "$('#calendar').fullCalendar('refetchEvents')"}),
            "start_date": forms.DateInput(attrs={"class": "form-control"}),
            "end_date": forms.DateInput(attrs={"class": "form-control"}),
            "comment": forms.Textarea(attrs={"class": "form-control"}),
        }

icu/apps/lending/views.py
from django.views.generic import ListView
from django.http import HttpResponse
from django.db.models import Q
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from icu.apps.lending.models import Item, Lending
from icu.apps.lending.forms import LendingForm
import json
from datetime import datetime


class ItemList(ListView):
    model = Item
    template_name = "item_list.html"
    context_object_name = "items"


@login_required
def calendar(request):
    items = Item.objects.all()
    users = User.objects.all()
    context_vars = {"items": items, "users": users}
    template_name = "calendar.html"
    context = RequestContext(request)
    return render_to_response(template_name, context_vars,  context_instance=context)


@login_required
def calendar_lendings(request):
    #colors = ["#006400", "#556B2F", "#808000", "#6B8E23", "#008000", "#2E8B57"]
    ret = []
    from_date = datetime.fromtimestamp(float(request.GET['start']))
    to_date = datetime.fromtimestamp(float(request.GET['end']))
    lendings = Lending.objects.filter(Q(start_date__range=(from_date, to_date)) | Q(end_date__range=(from_date, to_date))).distinct()
    if request.GET.get('item', None):
        lendings = lendings.filter(item_id=request.GET['item'])
    if request.GET.get('user', None):
        lendings = lendings.filter(user_id=request.GET['user'])
    for lending in lendings:
        if lending.user == request.user:
            color = "#22B24C"
        else:
            color = "#6B8E23"
        ret.append({"title": lending.item.name+" - "+lending.user.username,
                    "start": lending.start_date.strftime("%Y-%m-%d"),
                    "end": lending.end_date.strftime("%Y-%m-%d"),
                    "color": color,
                    "allDay": True,
                    "comment": lending.comment
        })
    return HttpResponse(content=json.dumps(ret), content_type="application/json")


@login_required
def borrow(request):
    context_vars = {}
    if request.method == "POST":
        form = LendingForm(request.POST)
        if form.is_valid():
            lending = form.save(commit=False)
            lending.user = request.user
            lending.save()
            form = LendingForm()
            context_vars.update({"success": "Your submission was successful"})
        else:
            ve = ""
            if '__all__' in form.errors:
                ve += u"{0}<br/>".format(form.errors['__all__'][0])
            for field in form:
                if field.errors:
                    for error in field.errors:
                        ve += u"{0}: {1}<br/>".format(field.label, error)
            context_vars.update({"failure": ve})
    else:
        initial = {}
        if request.GET.get('item', None):
            initial.update({"item": request.GET["item"]})
        form = LendingForm(initial=initial)
    context_vars.update({"form": form})
    template_name = "borrow.html"
    context = RequestContext(request)
    return render_to_response(template_name, context_vars,  context_instance=context)

icu/apps/lending/templates/base.html
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Lending app">
    <meta name="author" content="Andreas Porevopoulos, <sv1jsb@gmail.com>">
    <link rel="shortcut icon" href="{{ STATIC_URL }}ico/favicon.png">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}css/lending.css" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
      <script src="{{ STATIC_URL }}js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Lendings</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url "item_list" %}">Home</a></li>
            {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lendings <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url "calendar" %}">Calendar</a></li>
                <li><a href="{% url "borrow" %}">Borrow</a></li>
              </ul>
            </li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

icu/apps/lending/templates/borrow.html
{% extends "base.html" %}{% load url from future %}
{% block css %}
<link href="{{ STATIC_URL }}css/fullcalendar.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/datepicker.css" rel="stylesheet">
{% endblock %}
{% block js %}
<script src="{{ STATIC_URL }}js/fullcalendar.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-datepicker.min.js"></script>
<script>
$(document).ready(function(){
    var calendar = $("#calendar").fullCalendar({
        weekMode: 'liquid',
        firstDay: 1,
        aspectRatio: 0.85,
        eventClick: function(event){
          if(!$(this).hasClass("popped_over") && event.comment){
              $(this).popover({
                  content: event.comment,
                  placement: "auto top",
                  container: "body"
              });
              $(this).popover('show');
              $(this).addClass("popped_over");
          }
        },
        events: {
                url: '{% url "calendar_lendings" %}',
                data: function(){
                    var obj = {};
                    if($("#id_item").val()!=""){
                        obj.item = $("#id_item").val();
                    }
                    return obj;
                }
        }
    });
    var config_datepicker = {
        autoclose: true,
        format: "dd/mm/yyyy",
        weekStart: 1
    };
    $("#id_start_date").datepicker(config_datepicker);
    $("#id_end_date").datepicker(config_datepicker);
})
</script>
{% endblock %}
{% block title %}Borrow an item{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Borrow an item</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post" action="{% url "borrow" %}">{% csrf_token %}
                        <div class="form-group">
                            <label for="id_item">Item</label>
                            {{ form.item }}
                        </div>
                        <div class="form-group">
                            <label for="id_start_date">Start date</label>
                            <div class="input-group">
                            {{ form.start_date }}
                            <span class="input-group-addon"><i class="icon icon-calendar"></i></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_end_date">End date</label>
                            <div class="input-group">
                            {{ form.end_date }}
                            <span class="input-group-addon"><i class="icon icon-calendar"></i></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_comment">Comment</label>
                            {{ form.comment }}
                        </div>
                        <hr/>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Submit</button>
                           <button type="reset" class="btn btn-default pull-right">Reset</button>
                        </div>
                        {% if failure %}
                            <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong>Error!</strong> Your last action performed the following error(s):<br/>
                                {{ failure|safe }}
                            </div>
                        {% elif success %}
                            <div class="alert alert-success alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong>Success!</strong><br/>
                                {{ success|safe }}
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Availability</h3>
                </div>
                <div class="panel-body">
                    <div id="calendar"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

icu/apps/lending/templates/calendar.html
{% extends "base.html" %}{% load url from future %}
{% block css %}
<link href="{{ STATIC_URL }}css/fullcalendar.css" rel="stylesheet">
{% endblock %}
{% block js %}
<script src="{{ STATIC_URL }}js/fullcalendar.min.js"></script>
<script>
$(document).ready(function(){
    $("#calendar").fullCalendar({
        weekMode: 'liquid',
        firstDay: 1,
        aspectRatio: 0.85,
        eventClick: function(event){
          if(!$(this).hasClass("poped_over") && event.comment){
              $(this).popover({
                  content: event.comment,
                  placement: "auto top",
                  container: "body"
              });
              $(this).popover('show');
              $(this).addClass("poped_over");
          }
        },
        events: {
                url: '{% url "calendar_lendings" %}',
                data: function(){
                    var obj = {};
                    if($("#id_commodities").val()!=""){
                        obj.item = $("#id_commodities").val();
                    }
                    if($("#id_users").val()!=""){
                        obj.user = $("#id_users").val();
                    }
                    return obj;
                }
        }
    });
})
</script>
{% endblock %}
{% block title %}Calendar view{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-3 col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Filters</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="id_commodities">Commodities</label>
                        <select id="id_commodities" class="form-control" onchange="$('#calendar').fullCalendar('refetchEvents')">
                            <option value="">All commodities</option>
                            {% for item in items %}
                            <option value="{{ item.id }}">{{ item.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_users">Users</label>
                        <select id="id_users" class="form-control" onchange="$('#calendar').fullCalendar('refetchEvents')">
                            <option value="">All users</option>
                            {% for usr in users %}
                            <option value="{{ usr.id }}">{{ usr.username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-9">
            <div id="calendar">
            </div>
        </div>
    </div>
{% endblock %}

icu/apps/lending/templates/item_list.html
{% extends "base.html" %}{% load url from future %}
{% block title %}Lending items list{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h3>Commodities to let</h3>
            <table class="table table-bordered table-condensed">
                <thead>
                <tr class="item_list_head">
                    <th>Available</th>
                    <th>Commodity</th>
                    <th>Description</th>
                    <th>Max. duration</th>
                    <th>Image</th>
                </tr>
                </thead>
                <tbody>
                {% for item in items %}
                <tr class="{% if item.locked %}danger{% endif %}">
                    <td class="col-lg-1">{% if not item.locked %}<i class="icon icon-check"></i>{% else %}<i class="icon icon-check-empty"></i>{% endif %}</td>
                    <td class="col-lg-2">{% if not item.locked %}<a href="{% url "borrow" %}?item={{ item.id }}">{{ item.name }}</a>{% else %}{{ item.name }}{% endif %}</td>
                    <td class="col-lg-6">{{ item.description }}</td>
                    <td class="col-lg-1">{{ item.lending_duration|default_if_none:"" }}</td>
                    <td class="col-lg-2"><div class="thumbnail"><img src="{{ MEDIA_URL }}{{ item.image }}"/></div></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

icu/templates/documentation.html
{% extends "base.html" %}{% load url from future %}
{% block title %}Lendings documentation{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-10 col-md-10 col-lg-offset-2 col-md-offset-2">
            <h1>Documentation</h1>
            <p class="lead">
                Software used
            </p>
            <p>
                This application is using the bootstrap css theme which has it's main colors changed to #22B24C green.<br/>
                FontAwesome icons is also included to the theme.<br/>
                The calendar used is fullCalendar an add-on for jQuery.<br/>
            </p>
            <p class="lead">
                Usage instructions
            </p>
            <p>
                The lending app is accessible through the <a href="{% url "item_list" %}">Home</a> link at the navigation bar on top.
                This is a list of all items at you inventory. It displays availability, name, description, maximum lending duration,
                and image if available. If an item is not available its line will be colored red.
                The name of every item is a link and when clicked it will transfer the user to the <a href="{% url "borrow" %}">Borrow</a> page
                (if is logged in) with this item preselected and the availability calendar filtered for this item.
            </p>
            <p>
                Logged in users have access to the <a href="{% url "calendar" %}">Calendar</a> and <a href="{% url "borrow" %}">Borrow</a> pages.
                You can login through the <a href="/admin/">Admin</a> interface, since there is no login page provided.
                Login credentials are:
                <ul>
                    <li>Username: lending1, password: lending1</li>
                    <li>Username: lending2, password: lending2</li>
                </ul>
            </p>
            <p>
                The <a href="{% url "calendar" %}">Calendar</a> page displays all lendings by all users to a monthly paged calendar.
                Lendings of the current user are colored green, all other users' lendings are colored olive.
                Every lending displays the item name and the user username who have borrowed it. When a lending is clicked
                the comment, if any, is displayed as a popover.
                On the left side the are filters with which a user can filter the calendar.
                The <strong>Commodity</strong> filter filters the calendar according to the item selected by the user.
                The <strong>User</strong> filter filters the calendar according to the username selected by the user.
            </p>
            <p>
                The <a href="{% url "borrow" %}">Borrow</a> page is for submitting a lending. It displays the availability calendar
                of all items. When the user selects an item to borrow the calendar is filtered to only that. The drop down selection of items includes only
                the available for borrowing items. The start and end dates
                when clicked present a mini calendar with which the user can choose the dates he likes.
                The form does the following validations before a successful submission can be registered.
                <ul>
                    <li>Item, start date, end date are required.</li>
                    <li>Start date must be greater or equal than today.</li>
                    <li>End date must be greater or equal than start date.</li>
                    <li>The duration of lending must be less or equal to the maximum duration of the item.</li>
                    <li>Start and end date must not overlap another lending.</li>
                </ul>
                When all validations succeed the lending is registered and is displayed at the calendar.
            </p>
            <p class="lead">
                Settings
            </p>
            <p>
                The date input format have been set to <em>"dd/mm/yyyy"</em>, which can be changed at the settings.py file.<br/>
                The same setting is used for configuring the datepickers at borrow.html file.<br/>
                Calendars start at <em>Monday</em>.
            </p>
            <p class="lead">
                Testing
            </p>
            <p>
                A number of tests are provided for the lending application.<br/>
                <code>
                    python manage.py test lending
                </code>
            </p>
            <br/>
        </div>
    </div>
{% endblock %}